"""create academic state schema

Revision ID: 2191729eb9e3
Revises: 
Create Date: 2026-09-16 03:16:04.589319
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2191729eb9e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('roll_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_table('availability_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'LOCKED', name='availability_block_type'), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.CheckConstraint('block_date IS NOT NULL OR day_of_week IS NOT NULL', name='ck_availability_has_schedule'),
    sa.CheckConstraint('day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6', name='ck_availability_day'),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_times_ordered'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_blocks_student_id'), 'availability_blocks', ['student_id'], unique=False)
    op.create_table('change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_history_entity_id'), 'change_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_history_entity_type'), 'change_history', ['entity_type'], unique=False)
    op.create_index(op.f('ix_change_history_student_id'), 'change_history', ['student_id'], unique=False)
    op.create_table('personal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('event_type', sa.Enum('FIXED', 'PERSONAL', 'TRAVEL', 'HEALTH', 'OTHER', name='personal_event_type'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name='ck_personal_event_times_ordered'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_events_starts_at'), 'personal_events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_personal_events_student_id'), 'personal_events', ['student_id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'number', 'academic_year', name='uq_semester_student_number_year')
    )
    op.create_index(op.f('ix_semesters_student_id'), 'semesters', ['student_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='study_plan_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'plan_date', name='uq_study_plan_student_date')
    )
    op.create_index(op.f('ix_study_plans_plan_date'), 'study_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_table('academic_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('event_type', sa.Enum('INSTRUCTION', 'HOLIDAY', 'EXAM', 'DEADLINE', 'EVENT', name='calendar_event_type'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('ends_at >= starts_at', name='ck_calendar_event_times_ordered'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_calendar_events_semester_id'), 'academic_calendar_events', ['semester_id'], unique=False)
    op.create_index(op.f('ix_academic_calendar_events_starts_at'), 'academic_calendar_events', ['starts_at'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('kind', sa.Enum('THEORY', 'LAB', 'ELECTIVE', 'ACTIVITY', name='course_kind'), nullable=False),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('faculty_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'code', name='uq_course_semester_code')
    )
    op.create_index(op.f('ix_courses_semester_id'), 'courses', ['semester_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('NOTICE_BOARD', 'WHATSAPP', 'FACULTY', 'STUDENT', 'OTHER', name='announcement_source'), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_course_id'), 'announcements', ['course_id'], unique=False)
    op.create_index(op.f('ix_announcements_published_at'), 'announcements', ['published_at'], unique=False)
    op.create_index(op.f('ix_announcements_semester_id'), 'announcements', ['semester_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('assessment_type', sa.Enum('MID', 'SLIP_TEST', 'ASSIGNMENT', 'SKILL_TEST', 'DAY_TO_DAY', 'CONTINUOUS_ASSESSMENT', 'LAB_TEST', 'PRACTICAL', name='assessment_type'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', name='assessment_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maximum_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('earned_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weightage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('earned_marks IS NULL OR earned_marks >= 0', name='ck_assessment_earned_marks_nonnegative'),
    sa.CheckConstraint('maximum_marks IS NULL OR earned_marks IS NULL OR earned_marks <= maximum_marks', name='ck_assessment_earned_within_maximum'),
    sa.CheckConstraint('maximum_marks IS NULL OR maximum_marks > 0', name='ck_assessment_maximum_marks_positive'),
    sa.CheckConstraint('weightage IS NULL OR (weightage >= 0 AND weightage <= 100)', name='ck_assessment_weightage_range'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_course_id'), 'assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessments_scheduled_at'), 'assessments', ['scheduled_at'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maximum_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('earned_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('earned_marks IS NULL OR earned_marks >= 0', name='ck_assignment_earned_marks_nonnegative'),
    sa.CheckConstraint('maximum_marks IS NULL OR earned_marks IS NULL OR earned_marks <= maximum_marks', name='ck_assignment_earned_within_maximum'),
    sa.CheckConstraint('maximum_marks IS NULL OR maximum_marks > 0', name='ck_assignment_maximum_marks_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assignments_due_at'), 'assignments', ['due_at'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('attended_classes', sa.Integer(), nullable=False),
    sa.Column('conducted_classes', sa.Integer(), nullable=False),
    sa.Column('target_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attended_classes <= conducted_classes', name='ck_attendance_attended_not_over_conducted'),
    sa.CheckConstraint('attended_classes >= 0', name='ck_attendance_attended_nonnegative'),
    sa.CheckConstraint('conducted_classes >= 0', name='ck_attendance_conducted_nonnegative'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_course_id'), 'attendance', ['course_id'], unique=True)
    op.create_table('course_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('sequence > 0', name='ck_course_unit_sequence_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'sequence', name='uq_course_unit_sequence')
    )
    op.create_index(op.f('ix_course_units_course_id'), 'course_units', ['course_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_kind', sa.Enum('LECTURE', 'LAB', 'TUTORIAL', 'EXAM', 'OTHER', name='timetable_session_kind'), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_timetable_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_timetable_times_ordered'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_course_id'), 'timetable_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_semester_id'), 'timetable_entries', ['semester_id'], unique=False)
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('priority_type', sa.Enum('ASSESSMENT', 'ASSIGNMENT', 'ATTENDANCE', 'PREPARATION', 'OTHER', name='priority_type'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_priority_score_range'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priorities_assessment_id'), 'priorities', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_priorities_assignment_id'), 'priorities', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_priorities_calculated_at'), 'priorities', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_priorities_course_id'), 'priorities', ['course_id'], unique=False)
    op.create_index(op.f('ix_priorities_student_id'), 'priorities', ['student_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('risk_type', sa.Enum('ATTENDANCE', 'DEADLINE', 'PREPARATION', 'PERFORMANCE', 'WORKLOAD', 'CONFLICT', 'MISSED_TASK', name='risk_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_risk_score_range'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_assessment_id'), 'risks', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_risks_calculated_at'), 'risks', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_risks_course_id'), 'risks', ['course_id'], unique=False)
    op.create_index(op.f('ix_risks_student_id'), 'risks', ['student_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name='ck_topic_estimated_minutes_positive'),
    sa.CheckConstraint('sequence > 0', name='ck_topic_sequence_positive'),
    sa.ForeignKeyConstraint(['unit_id'], ['course_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'sequence', name='uq_topic_unit_sequence')
    )
    op.create_index(op.f('ix_topics_unit_id'), 'topics', ['unit_id'], unique=False)
    op.create_table('assessment_topics',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', 'topic_id')
    )
    op.create_table('study_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name='ck_study_progress_percentage_range'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'topic_id', name='uq_study_progress_student_topic')
    )
    op.create_index(op.f('ix_study_progress_student_id'), 'study_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_study_progress_topic_id'), 'study_progress', ['topic_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'SKIPPED', 'MOVED', name='study_session_status'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name='ck_study_session_times_ordered'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_course_id'), 'study_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_starts_at'), 'study_sessions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_study_sessions_study_plan_id'), 'study_sessions', ['study_plan_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_topic_id'), 'study_sessions', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_sessions_topic_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_study_plan_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_starts_at'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_course_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_study_progress_topic_id'), table_name='study_progress')
    op.drop_index(op.f('ix_study_progress_student_id'), table_name='study_progress')
    op.drop_table('study_progress')
    op.drop_table('assessment_topics')
    op.drop_index(op.f('ix_topics_unit_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_risks_student_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_course_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_calculated_at'), table_name='risks')
    op.drop_index(op.f('ix_risks_assessment_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_priorities_student_id'), table_name='priorities')
    op.drop_index(op.f('ix_priorities_course_id'), table_name='priorities')
    op.drop_index(op.f('ix_priorities_calculated_at'), table_name='priorities')
    op.drop_index(op.f('ix_priorities_assignment_id'), table_name='priorities')
    op.drop_index(op.f('ix_priorities_assessment_id'), table_name='priorities')
    op.drop_table('priorities')
    op.drop_index(op.f('ix_timetable_entries_semester_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_course_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_course_units_course_id'), table_name='course_units')
    op.drop_table('course_units')
    op.drop_index(op.f('ix_attendance_course_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_assignments_due_at'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_assessments_scheduled_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_course_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_announcements_semester_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_published_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_course_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_courses_semester_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_academic_calendar_events_starts_at'), table_name='academic_calendar_events')
    op.drop_index(op.f('ix_academic_calendar_events_semester_id'), table_name='academic_calendar_events')
    op.drop_table('academic_calendar_events')
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_plan_date'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_semesters_student_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_personal_events_student_id'), table_name='personal_events')
    op.drop_index(op.f('ix_personal_events_starts_at'), table_name='personal_events')
    op.drop_table('personal_events')
    op.drop_index(op.f('ix_change_history_student_id'), table_name='change_history')
    op.drop_index(op.f('ix_change_history_entity_type'), table_name='change_history')
    op.drop_index(op.f('ix_change_history_entity_id'), table_name='change_history')
    op.drop_table('change_history')
    op.drop_index(op.f('ix_availability_blocks_student_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    # PostgreSQL named enums outlive their tables. Remove them so a downgrade to
    # base can be followed by a clean upgrade in the same database.
    for enum_name in (
        'study_session_status',
        'study_plan_status',
        'severity',
        'risk_type',
        'priority_type',
        'personal_event_type',
        'timetable_session_kind',
        'assessment_status',
        'assessment_type',
        'announcement_source',
        'calendar_event_type',
        'course_kind',
        'availability_block_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
